spring.application.name=reto1
server.port=${PORT:8080}
spring.cloud.gcp.project-id=linko-training

# Limites de subida de archivos
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=105MB
